name: Docker CI/CD Workflow

on:
  push: 
    branches:
      - main          

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.prajaktanaik17}}
          password: ${{ secrets.Imcute@17}}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.prajaktanaik17 }}/simple-website:latest

  deploy:
    name: Deploy Docker Container
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.prajaktanaik17 }}
          password: ${{ secrets.Imcute@17 }}

      - name: Deploy the Container
        run: |
          docker pull ${{ secrets.prajaktanaik17 }}/simple-website:latest
          docker stop simple-website || true
          docker rm simple-website || true
          docker run -d --name simple-website -p 8080:80 ${{ secrets.prajaktanaik17 }}/simple-website:latest
